//! hostapd + dnsmasq backend: headless/server installs without
//! NetworkManager. We own every artifact (configs + pidfiles live in
//! `/run/aetherlink`), so teardown is exact.
//!
//! Client DNS: dnsmasq hands itself out as the resolver and forwards
//! upstream to the host resolver — which the client forces into the tunnel
//! while up (DNS_NO_LEAK) and which falls back to the ISP when down.

use crate::config::{HotspotConfig, SubnetPlan};
use crate::{run, run_quiet, HotspotError, Result};

/// Runtime dir for generated configs/pidfiles.
pub const RUN_DIR: &str = "/run/aetherlink";

pub const HOSTAPD_CONF: &str = "/run/aetherlink/hostapd.conf";
pub const DNSMASQ_CONF: &str = "/run/aetherlink/dnsmasq.conf";
pub const HOSTAPD_PID: &str = "/run/aetherlink/hostapd.pid";
pub const DNSMASQ_PID: &str = "/run/aetherlink/dnsmasq.pid";

/// Render `hostapd.conf` (pure; WPA2-PSK, 2.4GHz ACS by default — works on
/// every WiFi NIC; 5GHz is a knob for later).
#[must_use]
pub fn hostapd_conf(cfg: &HotspotConfig, iface: &str) -> String {
    let psk = cfg.password.clone().unwrap_or_default();
    format!(
        "# Generated by aetherlink-hotspot; do not edit (recreated on up).\n\
         interface={iface}\n\
         driver=nl80211\n\
         ssid={ssid}\n\
         hw_mode=g\n\
         channel=0\n\
         ieee80211n=1\n\
         wpa=2\n\
         wpa_key_mgmt=WPA-PSK\n\
         wpa_pairwise=CCMP\n\
         rsn_pairwise=CCMP\n\
         wpa_passphrase={psk}\n\
         ignore_broadcast_ssid=0\n",
        ssid = cfg.ssid
    )
}

/// Render `dnsmasq.conf` (pure): DHCP on the hotspot subnet, gateway + DNS
/// = our address on it, upstream = the host resolver (no `no-resolv`:
/// reading `/etc/resolv.conf` is exactly how we follow the tunnel DNS).
#[must_use]
pub fn dnsmasq_conf(iface: &str, plan: &SubnetPlan) -> String {
    format!(
        "# Generated by aetherlink-hotspot; do not edit (recreated on up).\n\
         interface={iface}\n\
         bind-interfaces\n\
         dhcp-range={start},{end},24h\n\
         dhcp-option=3,{gw}\n\
         dhcp-option=6,{gw}\n\
         no-hosts\n\
         pid-file={DNSMASQ_PID}\n",
        start = plan.dhcp_start,
        end = plan.dhcp_end,
        gw = plan.gateway
    )
}

/// Does the kernel consider this interface wireless?
#[must_use]
pub fn is_wireless(iface: &str) -> bool {
    std::path::Path::new(&format!("/sys/class/net/{iface}/wireless")).exists()
}

/// Wireless interfaces on this box (`/sys/class/net/*/wireless`), up.
#[must_use]
pub fn wireless_ifaces() -> Vec<String> {
    let Ok(entries) = std::fs::read_dir("/sys/class/net") else {
        return Vec::new();
    };
    entries
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|name| is_wireless(name))
        .collect()
}

/// Resolve the interface without NM: explicit (must be wireless) or the
/// first wireless device.
pub fn resolve_iface(iface: Option<&str>) -> Result<String> {
    match iface {
        Some(want) => {
            if is_wireless(want) {
                Ok(want.to_string())
            } else {
                Err(HotspotError::Config(format!(
                    "'{want}' is not a wireless interface (/sys/class/net/{want}/wireless missing)"
                )))
            }
        }
        None => wireless_ifaces()
            .into_iter()
            .next()
            .ok_or_else(|| HotspotError::Tool("no wireless interface found".to_string())),
    }
}

/// If NetworkManager runs this box, it will fight hostapd for the WiFi
/// device (auto-connect grabs the channel, hostapd dies). Detach it for the
/// AP's lifetime. Returns true only if WE flipped it to unmanaged (so down
/// restores exactly that and never touches a deliberately-unmanaged device).
#[must_use]
pub fn detach_from_nm(iface: &str) -> bool {
    if !crate::nm::nm_running() {
        return false;
    }
    // Current managed state of this exact device (skip already-unmanaged).
    let state = run(
        "nmcli",
        &[
            "-g".to_string(),
            "GENERAL.STATE".to_string(),
            "device".to_string(),
            "show".to_string(),
            iface.to_string(),
        ],
    )
    .unwrap_or_default();
    if state.contains("unmanaged") {
        return false;
    }
    crate::run_quiet(
        "nmcli",
        &[
            "device".to_string(),
            "set".to_string(),
            iface.to_string(),
            "managed".to_string(),
            "no".to_string(),
        ],
    );
    crate::log(&format!("hostapd: {iface} set unmanaged in NetworkManager"));
    true
}

/// Reverse of [`detach_from_nm`] (best-effort).
pub fn reattach_to_nm(iface: &str) {
    if !crate::nm::nm_running() {
        return;
    }
    crate::run_quiet(
        "nmcli",
        &[
            "device".to_string(),
            "set".to_string(),
            iface.to_string(),
            "managed".to_string(),
            "yes".to_string(),
        ],
    );
    crate::log(&format!("hostapd: {iface} handed back to NetworkManager"));
}

/// Bring the AP up: configs, address, hostapd, dnsmasq. Returns whether the
/// WiFi device was detached from NetworkManager (persisted for `down`).
pub fn up(cfg: &HotspotConfig, iface: &str, plan: &SubnetPlan) -> Result<bool> {
    std::fs::create_dir_all(RUN_DIR)
        .map_err(|e| HotspotError::Tool(format!("create {RUN_DIR}: {e}")))?;
    // Stop any stale daemons from a crashed run BEFORE writing fresh
    // configs (down_quiet removes them).
    down_quiet();
    let nm_unmanaged = detach_from_nm(iface);
    // Any failure below must undo every partial artifact: the state file is
    // only written by the caller after Ok, so down_quiet() cannot derive
    // what to remove — clean up here by hand.
    let r = up_inner(cfg, iface, plan);
    if r.is_err() {
        kill_pidfile(HOSTAPD_PID);
        kill_pidfile(DNSMASQ_PID);
        remove_addr(iface, plan);
        for f in [HOSTAPD_CONF, DNSMASQ_CONF, HOSTAPD_PID, DNSMASQ_PID] {
            let _ = std::fs::remove_file(f);
        }
        if nm_unmanaged {
            reattach_to_nm(iface);
        }
    }
    r.map(|()| nm_unmanaged)
}

fn up_inner(cfg: &HotspotConfig, iface: &str, plan: &SubnetPlan) -> Result<()> {
    std::fs::write(HOSTAPD_CONF, hostapd_conf(cfg, iface))
        .map_err(|e| HotspotError::Tool(format!("write {HOSTAPD_CONF}: {e}")))?;
    std::fs::write(DNSMASQ_CONF, dnsmasq_conf(iface, plan))
        .map_err(|e| HotspotError::Tool(format!("write {DNSMASQ_CONF}: {e}")))?;
    // Address the AP interface (clients get this as gateway/DNS).
    let cidr = format!("{}/{}", plan.gateway, plan.prefix);
    run(
        "ip",
        &[
            "addr".to_string(),
            "replace".to_string(),
            cidr,
            "dev".to_string(),
            iface.to_string(),
        ],
    )?;
    run(
        "ip",
        &[
            "link".to_string(),
            "set".to_string(),
            "dev".to_string(),
            iface.to_string(),
            "up".to_string(),
        ],
    )?;
    // hostapd daemonizes itself (-B) and writes its pidfile.
    if let Err(e) = run(
        "hostapd",
        &[
            "-B".to_string(),
            "-P".to_string(),
            HOSTAPD_PID.to_string(),
            HOSTAPD_CONF.to_string(),
        ],
    ) {
        return Err(HotspotError::Tool(format!(
            "{e} (install: apt install hostapd; check RF kill: rfkill list)"
        )));
    }
    // Give hostapd a moment to fail on channel/rfkill problems.
    std::thread::sleep(std::time::Duration::from_millis(500));
    if !pid_alive(HOSTAPD_PID) {
        return Err(HotspotError::Tool(
            "hostapd exited right after start (rfkill? bad channel? see journalctl -u hostapd / syslog)"
                .to_string(),
        ));
    }
    if let Err(e) = run("dnsmasq", &["--conf-file".to_string(), DNSMASQ_CONF.to_string()]) {
        // Full cleanup happens in up()'s error handler.
        return Err(HotspotError::Tool(format!(
            "{e} (install: apt install dnsmasq)"
        )));
    }
    Ok(())
}

/// Drop the gateway address `up` put on the AP interface (best-effort).
fn remove_addr(iface: &str, plan: &SubnetPlan) {
    let cidr = format!("{}/{}", plan.gateway, plan.prefix);
    run_quiet(
        "ip",
        &[
            "addr".to_string(),
            "del".to_string(),
            cidr,
            "dev".to_string(),
            iface.to_string(),
        ],
    );
}

/// Kill the daemons, remove the address/configs (best-effort, traced).
pub fn down_quiet() {
    for pidfile in [HOSTAPD_PID, DNSMASQ_PID] {
        kill_pidfile(pidfile);
    }
    if let Ok(st) = crate::state::load() {
        if let Some(st) = st {
            if let Ok(plan) = crate::config::subnet_plan(&st.subnet) {
                remove_addr(&st.interface, &plan);
            }
            if st.nm_unmanaged {
                reattach_to_nm(&st.interface);
            }
        }
    }
    for f in [HOSTAPD_CONF, DNSMASQ_CONF, HOSTAPD_PID, DNSMASQ_PID] {
        let _ = std::fs::remove_file(f);
    }
}

/// Both daemons alive?
#[must_use]
pub fn is_alive() -> bool {
    pid_alive(HOSTAPD_PID) && pid_alive(DNSMASQ_PID)
}

/// Read a pidfile and signal-liveness probe it (kill -0).
#[must_use]
pub fn pid_alive(pidfile: &str) -> bool {
    let Some(pid) = read_pid(pidfile) else {
        return false;
    };
    // `kill -0` = existence probe without a signal.
    std::process::Command::new("kill")
        .args(["-0", &pid.to_string()])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

/// Valid pid from a pidfile, if any.
fn read_pid(pidfile: &str) -> Option<i32> {
    let raw = std::fs::read_to_string(pidfile).ok()?;
    let pid = raw.trim().parse::<i32>().ok()?;
    (pid > 0).then_some(pid)
}

/// SIGTERM the process behind a pidfile (idempotent).
fn kill_pidfile(pidfile: &str) {
    if let Some(pid) = read_pid(pidfile) {
        run_quiet("kill", &["-TERM".to_string(), pid.to_string()]);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> HotspotConfig {
        HotspotConfig {
            password: Some("secret-pass-1".to_string()),
            ssid: "AetherLink".to_string(),
            ..HotspotConfig::default()
        }
    }

    fn plan() -> SubnetPlan {
        crate::config::subnet_plan("192.168.243.0/24").expect("plan")
    }

    #[test]
    fn hostapd_conf_is_wpa2_ap() {
        let conf = hostapd_conf(&cfg(), "wlan0");
        assert!(conf.contains("interface=wlan0"));
        assert!(conf.contains("ssid=AetherLink"));
        assert!(conf.contains("wpa=2"));
        assert!(conf.contains("wpa_key_mgmt=WPA-PSK"));
        assert!(conf.contains("wpa_passphrase=secret-pass-1"));
        assert!(conf.contains("rsn_pairwise=CCMP"));
        assert!(conf.contains("channel=0"), "ACS picks a free channel");
    }

    #[test]
    fn dnsmasq_serves_subnet_and_tunnel_following_dns() {
        let conf = dnsmasq_conf("wlan0", &plan());
        assert!(conf.contains("interface=wlan0"));
        assert!(conf.contains("dhcp-range=192.168.243.100,192.168.243.199,24h"));
        // Router + DNS = our gateway address on the hotspot subnet.
        assert!(conf.contains("dhcp-option=3,192.168.243.1"));
        assert!(conf.contains("dhcp-option=6,192.168.243.1"));
        // Must read the host resolv.conf so tunnel DNS is followed; an
        // explicit server= would bypass the tunnel-forced resolver.
        assert!(!conf.contains("no-resolv"));
        assert!(!conf.contains("server="));
    }
}
