//! TDD: Linux network capture/apply helpers (no privs needed).
//!
//! Pure parsers over canned `ip route` / `resolvectl` / resolv.conf output
//! plus arg builders for `ip`/`resolvectl`. Mirrors `windows_net.rs` for
//! the Linux platform task. Live read-only probe at the end (cfg-gated).

use aetherlink_client::platform::linux::{
    ip_addr_add_args, ip_link_del_args, ip_link_up_args, ip_route_add_via_args,
    ip_route_add_via_dev_args, ip_route_del_args, parse_ip_route, parse_resolv_conf,
    parse_resolvectl_dns, resolvectl_dns_args, resolvectl_dns_query_args,
    resolvectl_domain_args, resolvectl_revert_args, route_dest_cidr,
};

const IP_ROUTE: &str = "\
default via 192.168.31.1 dev wlan0 proto dhcp metric 600\n\
169.254.0.0/16 dev wlan0 scope link metric 1000\n\
192.168.31.0/24 dev wlan0 proto kernel scope link src 192.168.31.95 metric 600\n\
192.168.122.0/24 via 192.168.31.254 dev wlan0 proto static metric 600\n\
blackhole 10.0.0.0/8 proto static\n\
unreachable 203.0.113.0/24\n\
";

#[test]
fn parse_ip_route_finds_default_and_gateways() {
    let table = parse_ip_route(IP_ROUTE);
    assert_eq!(
        table.default_via,
        Some("192.168.31.1".parse().expect("gw"))
    );
    assert_eq!(table.default_dev.as_deref(), Some("wlan0"));
    // Gatewayed rows kept (default + the static via-row); connected rows
    // and blackhole/unreachable dropped.
    assert_eq!(table.routes.len(), 2);
    assert_eq!(table.routes[0].dest, "default");
    assert_eq!(table.routes[0].via, "192.168.31.1");
    assert_eq!(table.routes[1].dest, "192.168.122.0/24");
    assert_eq!(table.routes[1].via, "192.168.31.254");
}

#[test]
fn parse_ip_route_empty_has_no_default() {
    let table = parse_ip_route("");
    assert!(table.default_via.is_none());
    assert!(table.default_dev.is_none());
    assert!(table.routes.is_empty());
}

#[test]
fn parse_ip_route_multi_default_keeps_lowest_metric() {
    // Multi-homed box: the kernel routes traffic through the LOWEST-metric
    // default regardless of the dump order; the snapshot must bind to it.
    let out = "\
default via 192.168.1.1 dev wlan0 proto dhcp metric 600\n\
default via 10.0.0.1 dev eth0 proto dhcp metric 100\n\
";
    let table = parse_ip_route(out);
    assert_eq!(table.default_via, Some("10.0.0.1".parse().expect("gw")));
    assert_eq!(table.default_dev.as_deref(), Some("eth0"));
    assert_eq!(table.default_metric, Some(100));
}

#[test]
fn parse_resolvectl_dns_extracts_servers() {
    let out = "Link 3 (wlan0): 192.168.31.1 8.8.8.8\n";
    assert_eq!(
        parse_resolvectl_dns(out),
        vec!["192.168.31.1".to_string(), "8.8.8.8".to_string()]
    );
    // A tunnel-forced link shows the virtual resolver (stale-up detection).
    let forced = "Link 3 (wlan0): 10.255.0.1\n";
    assert_eq!(parse_resolvectl_dns(forced), vec!["10.255.0.1".to_string()]);
}

#[test]
fn parse_resolv_conf_nameservers_only() {
    let text = "# Generated by NetworkManager\n\
                nameserver 127.0.0.53\n\
                options edns0 trust-ad\n\
                nameserver 1.1.1.1\n";
    assert_eq!(
        parse_resolv_conf(text),
        vec!["127.0.0.53".to_string(), "1.1.1.1".to_string()]
    );
}

#[test]
fn arg_builders_match_iproute2_and_resolvectl() {
    let gw: std::net::Ipv4Addr = "192.168.31.1".parse().unwrap();
    assert_eq!(
        ip_addr_add_args("aether0", "10.255.0.2/30"),
        ["addr", "add", "10.255.0.2/30", "dev", "aether0"]
    );
    assert_eq!(
        ip_link_up_args("aether0", 1400),
        ["link", "set", "dev", "aether0", "mtu", "1400", "up"]
    );
    assert_eq!(ip_link_del_args("aether0"), ["link", "del", "aether0"]);
    assert_eq!(
        ip_route_add_via_args("93.184.216.34/32", &gw),
        ["route", "add", "93.184.216.34/32", "via", "192.168.31.1"]
    );
    let dns: std::net::Ipv4Addr = "10.255.0.1".parse().unwrap();
    assert_eq!(
        ip_route_add_via_dev_args("0.0.0.0/1", &dns, "aether0"),
        ["route", "add", "0.0.0.0/1", "via", "10.255.0.1", "dev", "aether0"]
    );
    assert_eq!(ip_route_del_args("0.0.0.0/1"), ["route", "del", "0.0.0.0/1"]);
    assert_eq!(
        resolvectl_dns_args("wlan0", &dns),
        ["dns", "wlan0", "10.255.0.1"]
    );
    assert_eq!(resolvectl_dns_query_args("wlan0"), ["dns", "wlan0"]);
    assert_eq!(resolvectl_domain_args("wlan0"), ["domain", "wlan0", "~."]);
    assert_eq!(resolvectl_revert_args("wlan0"), ["revert", "wlan0"]);
}

#[test]
fn route_dest_cidr_normalizes_and_rejects_ranges() {
    assert_eq!(
        route_dest_cidr("203.0.113.7"),
        Some("203.0.113.7/32".to_string())
    );
    assert_eq!(
        route_dest_cidr("198.51.100.0/24"),
        Some("198.51.100.0/24".to_string())
    );
    // ip_range rules have no iproute2 form and must be rejected upstream.
    assert_eq!(route_dest_cidr("203.0.113.10-203.0.113.50"), None);
}

/// Live read-only probe (Linux only): `ip -4 route` parses on the real box.
#[cfg(target_os = "linux")]
#[test]
fn live_ip_route_parses() {
    let out = std::process::Command::new("ip")
        .args(["-4", "route", "show"])
        .output()
        .expect("iproute2 is expected on Linux");
    if !out.status.success() {
        return; // exotic sandbox without `ip`
    }
    let text = String::from_utf8_lossy(&out.stdout);
    let table = parse_ip_route(&text);
    // A default route is typical but not guaranteed (containers); if one is
    // there, it must have both a gateway and a device.
    if text.lines().any(|l| l.starts_with("default via")) {
        assert!(table.default_via.is_some());
        assert!(table.default_dev.is_some());
    }
}
